# Generated by Django 4.0.4 on 2022-06-08 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_title', models.CharField(max_length=200)),
                ('closet_url', models.CharField(max_length=300)),
                ('closet_create_date', models.DateTimeField(auto_now=True)),
                ('closet_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Closet_onepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_onepiece_title', models.CharField(default='', max_length=200)),
                ('closet_onepiece_url', models.CharField(default='', max_length=50)),
                ('closet_onepiece_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('closet_onepiece_spring', models.BooleanField(default=True)),
                ('closet_onepiece_summer', models.BooleanField(default=True)),
                ('closet_onepiece_autumn', models.BooleanField(default=True)),
                ('closet_onepiece_windter', models.BooleanField(default=True)),
                ('closet_onepiece_color', models.CharField(default='', max_length=100)),
                ('closet_onepiece_style', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Closet_outer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_outer_title', models.CharField(default='', max_length=200)),
                ('closet_outer_url', models.CharField(default='', max_length=50)),
                ('closet_outer_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('closet_outer_spring', models.BooleanField(default=True)),
                ('closet_outer_summer', models.BooleanField(default=True)),
                ('closet_outer_autumn', models.BooleanField(default=True)),
                ('closet_outer_windter', models.BooleanField(default=True)),
                ('closet_outer_color', models.CharField(default='', max_length=100)),
                ('closet_outer_style', models.CharField(default='', max_length=100)),
                ('closet_outer_fit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Closet_pants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_pants_title', models.CharField(default='', max_length=200)),
                ('closet_pants_url', models.CharField(default='', max_length=50)),
                ('closet_pants_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('closet_pants_spring', models.BooleanField(default=True)),
                ('closet_pants_summer', models.BooleanField(default=True)),
                ('closet_pants_autumn', models.BooleanField(default=True)),
                ('closet_pants_windter', models.BooleanField(default=True)),
                ('closet_pants_color', models.CharField(default='', max_length=100)),
                ('closet_pants_style', models.CharField(default='', max_length=100)),
                ('closet_pants_fit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Closet_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closet_top_title', models.CharField(default='', max_length=200)),
                ('closet_top_url', models.CharField(default='', max_length=50)),
                ('closet_top_uploadedFile', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('closet_top_spring', models.BooleanField(default=True)),
                ('closet_top_summer', models.BooleanField(default=True)),
                ('closet_top_autumn', models.BooleanField(default=True)),
                ('closet_top_windter', models.BooleanField(default=True)),
                ('closet_top_color', models.CharField(default='', max_length=100)),
                ('closet_top_style', models.CharField(default='', max_length=100)),
                ('closet_top_fit', models.FloatField(default=1.0, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
            ],
        ),
    ]