# Generated by Django 4.0.2 on 2022-06-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_closet_author_closet_onepiece_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='closet_onepiece',
            old_name='closet_onepiece_url',
            new_name='closet_url',
        ),
        migrations.RenameField(
            model_name='closet_outer',
            old_name='closet_outer_url',
            new_name='closet_url',
        ),
        migrations.RenameField(
            model_name='closet_pants',
            old_name='closet_pants_url',
            new_name='closet_url',
        ),
        migrations.RenameField(
            model_name='closet_top',
            old_name='closet_top_url',
            new_name='closet_url',
        ),
    ]
